import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header"
import Footer from "../components/footer"

export const metadata: Metadata = {
  title: "METs Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body 
      className="flex flex-col min-h-screen max-w-5xl mx-auto my-4 w-[calc(100%-36px)]">
        {<Header />}
        <main className="grow mt-4">
          {children}
        </main>
        {<Footer />}
      </body>
    </html>
  );
}
